name: "capitec-spring-boot-app"
enabled: true
person:
    name: "Ting-I"
    surname: "Liang"
spring:
    application:
        name: config-client
    config:
        import: optional:configserver:http://10.43.244.121:8888
    cloud:
        config:
            label: main
            username: root
            password: s3cr3t
